// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhTmysW8dCJQl80iEC2VEseWAShJuruKA',
    appId: '1:627802907244:web:7e507e8d318076d3936e49',
    messagingSenderId: '627802907244',
    projectId: 'bidndrive-65be3',
    authDomain: 'bidndrive-65be3.firebaseapp.com',
    storageBucket: 'bidndrive-65be3.firebasestorage.app',
    measurementId: 'G-T2L3XCMWG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGNOFZZixqftQQKIO5wrt7Iplb8fbhmMk',
    appId: '1:627802907244:android:8730cbe56efdcd7e936e49',
    messagingSenderId: '627802907244',
    projectId: 'bidndrive-65be3',
    storageBucket: 'bidndrive-65be3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWQ_IVq-AQl9Pu_sy3GFIVguVEa3Fy3rY',
    appId: '1:627802907244:ios:9097e4190659011a936e49',
    messagingSenderId: '627802907244',
    projectId: 'bidndrive-65be3',
    storageBucket: 'bidndrive-65be3.firebasestorage.app',
    iosBundleId: 'com.example.bidDriving',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWQ_IVq-AQl9Pu_sy3GFIVguVEa3Fy3rY',
    appId: '1:627802907244:ios:9097e4190659011a936e49',
    messagingSenderId: '627802907244',
    projectId: 'bidndrive-65be3',
    storageBucket: 'bidndrive-65be3.firebasestorage.app',
    iosBundleId: 'com.example.bidDriving',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhTmysW8dCJQl80iEC2VEseWAShJuruKA',
    appId: '1:627802907244:web:b1884020339f96b5936e49',
    messagingSenderId: '627802907244',
    projectId: 'bidndrive-65be3',
    authDomain: 'bidndrive-65be3.firebaseapp.com',
    storageBucket: 'bidndrive-65be3.firebasestorage.app',
    measurementId: 'G-EX5MYDG6BX',
  );
}
